substitutions:
  _REGION: northamerica-northeast2
  _BUCKET: bot-detection-frontend-20250929

steps:
  - name: 'node:18'
    id: 'Install dependencies'
    entrypoint: 'bash'
    args:
      - -c
      - |
        cd frontend
        npm ci

  - name: 'node:18'
    id: 'Build frontend'
    entrypoint: 'bash'
    args:
      - -c
      - |
        cd frontend
        cp .env.production .env
        npm run build

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Upload to GCS'
    entrypoint: 'bash'
    args:
      - -c
      - |
        # Upload build artifacts to GCS bucket
        gcloud storage rsync -r frontend/dist gs://${_BUCKET}
        
        # Set cache control for index.html (no cache)
        gcloud storage objects update gs://${_BUCKET}/index.html --cache-control="no-cache"
        
        # Set cache control for assets (long cache)
        gcloud storage objects update gs://${_BUCKET}/assets/** --cache-control="public, max-age=31536000, immutable"

options:
  logging: CLOUD_LOGGING_ONLY
